### PR TITLE
Disable adminer in several environments

### PR DESCRIPTION
**Pull request by huszerldani**
Added an env variable for enabling/disabling adminer. It is useful for a production environment.

### CODE REVIEW

**Comment by huszerldani** [comment]
Hi!
I really like your package, but I need to disable it in production environment, so I made an env variable called `ADMINER_ENABLED` with default false.

**Comment by inmanturbo** [comment]
Hi @huszerldani 

This package does not automatically register its provider. One thing thing you can do in the meantime is conditionally register it. I'm using the following in a few projects:

```php
/** 
* Register any application services. 
* 
* @return void 
*/ 
public function register() 
{ 
    // register adminer but only in local environment     if($this->app->environment(['local', 'dev'])) { 
        $this->app->register(\Onecentlin\Adminer\ServiceProvider::class); 
    } 
}
```

**Comment by inmanturbo** [comment]
Hi @huszerldani 

This package does not automatically register its provider. One thing thing you can do in the meantime is conditionally register it. I'm using the following in a few projects:

```php
/** 
* Register any application services. 
* 
* @return void 
*/ 
public function register() 
{ 
    // register adminer but only in local environment     if($this->app->environment(['local', 'dev'])) { 
        $this->app->register(\Onecentlin\Adminer\ServiceProvider::class); 
    } 
}
```

Sorry about the formatting. Posting from my phone atm

**Comment by huszerldani** [comment]
Thank you! 🙏

**Pull request merged**
